autoservice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('automobiliai/',  views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:automobilis_id>', views.automobilis, name='automobilis'),
    path('uzsakymai/', views.UzsakymaiListView.as_view(), name='uzsakymai'),
    path('uzsakymai/<int:pk>', views.UzsakymasDetailView.as_view(), name='uzsakymas'),
    path('search/', views.search, name='search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('autoservice/', include('autoservice.urls')),
    path('', RedirectView.as_view(url='autoservice/', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

autoservice/models.py
from django.db import models


# Create your models here.


class Paslauga(models.Model):
    pavadinimas = models.CharField('Pavadinimas', max_length=200, help_text='Įveskite paslaugos pavadinimą')
    kaina = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name = 'Paslauga'
        verbose_name_plural = 'Paslaugos'

    def __str__(self):
        return self.pavadinimas


def validate_at_least_one_digit(value):
    if not any(char.isdigit() for char in value):
        raise ValueError('Neteisingai įvestas automobilio numeris.')

class Automobilis(models.Model):
    valstybinis_nr = models.CharField('Valstybinis_NR', max_length=6, validators=[validate_at_least_one_digit],
                                      help_text='Įvestas automobilio numeris turi turėti bent vieną skaičių.')
    automobilio_modelis_id = models.ForeignKey('Automobilio_modelis', on_delete=models.CASCADE)
    vin_kodas = models.CharField('VIN_kodas', max_length=17, help_text='Įveskite automobilio VIN kodą')
    klientas = models.CharField('Klientas', max_length=200, help_text='Įveskite aptarnaujamo žmogaus vardą pavardę')
    nuotrauka = models.ImageField('Mašina', upload_to='images', null=True, blank=True)

    def display_automobilis(self):
        return f'{self.automobilio_modelis_id.marke}, {self.automobilio_modelis_id.modelis}'

    display_automobilis.short_description = 'Automobilis'

    class Meta:
        verbose_name = 'Automobilis'
        verbose_name_plural = 'Automobiliai'

    def __str__(self):
        return f'{self.klientas}, Valstybinis Nr: {self.valstybinis_nr}'


class Automobilio_modelis(models.Model):
    marke = models.CharField('Markė', max_length=30)
    modelis = models.CharField('Modelis', max_length=50)

    class Meta:
        verbose_name = 'Automobilio_modelis'
        verbose_name_plural = 'Automobilio_modeliai'

    def __str__(self):
        return f'{self.marke}, {self.modelis}'


class Uzsakymas(models.Model):
    data = models.DateField('Uzsakymo_data')
    automobilis_id = models.ForeignKey('Automobilis', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Užsakymas'
        verbose_name_plural = 'Užsakymai'

    SERVIZO_STATUSAS = (
        ('r', 'Rezervuota'),
        ('a', 'Atšaukta'),
        ('t', 'Atlikta'),
        ('v', 'Vykdoma'),
    )

    status = models.CharField(max_length=1, choices=SERVIZO_STATUSAS, help_text='Statusas')

    def __str__(self):
        return str(self.automobilis_id)


class Uzsakymo_eilute(models.Model):
    paslauga_id = models.ForeignKey('Paslauga', on_delete=models.CASCADE)
    uzsakymas_id = models.ForeignKey('Uzsakymas', on_delete=models.CASCADE)
    kiekis = models.PositiveIntegerField('Kiekis', help_text='Įveskite kiekį')

    class Meta:
        verbose_name = 'Užsakymo_lentelė'
        verbose_name_plural = 'Užsakymų_lentelė'

    def __str__(self):
        return f'{self.uzsakymas_id} Paslauga: {self.paslauga_id}'

autoservice/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Paslauga, Uzsakymas, Automobilis, Automobilio_modelis, Uzsakymo_eilute


def index(request):
    services_count = Paslauga.objects.count()
    orders_count = Uzsakymas.objects.count()
    cars_count = Automobilis.objects.count()

    context = {
        'services_count': services_count,
        'orders_count': orders_count,
        'cars_count': cars_count,
    }

    return render(request, 'index.html', context)


def automobiliai(request):
    paginator = Paginator(Automobilis.objects.all(), 2)
    page_number = request.GET.get('page')
    automobiliai = paginator.get_page(page_number)
    context = {
        'automobiliai': automobiliai
    }
    return render(request, 'automobiliai.html', context=context)


def automobilis(request, automobilis_id):
    automobilis = get_object_or_404(Automobilis, pk=automobilis_id)
    return render(request, 'automobilis.html', {'automobilis': automobilis})


def search(request):
    query = request.GET.get('query')
    search_results = Automobilis.objects.filter(
        Q(vin_kodas__icontains=query) | Q(valstybinis_nr__icontains=query) | Q(klientas__icontains=query))
    search_results_2 = Automobilio_modelis.objects.filter(Q(marke__icontains=query) | Q(modelis__icontains=query))
    context = {
        'automobiliai': search_results,
        'automobilio_modelis': search_results_2,
        'query': query,
    }
    return render(request, 'search.html', context)


class UzsakymaiListView(generic.ListView):
    model = Uzsakymas
    paginate_by = 2
    template_name = 'uzsakymu_sarasas.html'


class UzsakymasDetailView(generic.DetailView):
    model = Uzsakymo_eilute
    template_name = 'uzsakymas.html'

templates/automobiliai.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h1>Automobiliai</h1>
    <p>Šiuo metu turime šiuos automobilius, kurie yra užregistruoti.</p>
    {% load static %}
    <div class="row">
      {% for a in automobiliai %}
        <div class="col-md-4 mb-4">
          <div class="card h-100 shadow">
            {% if a.nuotrauka %}
              <img src="{{ a.nuotrauka.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'images/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">{{ a.automobilio.modelis_id }}</h6>
              <p class="card-text"><a href="{{ a.id }}">{{a.klientas}} - {{ a.valstybinis_nr }}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="container puslapiai">
    <nav aria-label="...">
      {% if automobiliai.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
          {% for i in automobiliai.paginator.page_range %}
            {% if automobiliai.number == i %}
              <li class="page-item active">
                <a class="page-link">{{ i }}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}
    </nav>
  </div>
{% endblock %}

templates/automobilis.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h1>Automobilio informacija</h1>
    <ul class="automobilio savininkas">
      <li>Savininkas: {{automobilis.klientas}}</li>
      <li>Valstybinis Nr.: {{automobilis.valstybinis_nr}}</li>
      <li>Gamintojas: {{automobilis.automobilio_modelis_id.marke}}</li>
      <li>Modelis: {{automobilis.automobilio_modelis_id.modelis}}</li>
      <li>VIN kodas: {{automobilis.vin_kodas}}</li>
    </ul>
    <a href="{% url 'automobiliai' %}" class="btn btn-secondary mt-3">Atgal</a>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
  <title>Auto_Servisas</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body class="">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <div class="text-center mb-4">
          <a class="navbar-brand" href="#">
            {% if user.is_authenticated %}
              <svg class="bi bi-person" width="3em" height="3em" viewBox="0 0 16 16" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                  d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                  clip-rule="evenodd" />
              </svg>
              <p class="mb-0">{{ user.get_username }}</p>
            </a>
            {% endif %}
        </div>
        <ul class="sidebar-nav">
          <p><a href="{% url 'index' %}">Pradžia</a></p>
          <p><a href="{% url 'automobiliai' %}">Automobiliai</a></p>
          <p><a href="{% url 'uzsakymai' %}">Užsakymai</a></p>
        </ul>

        <form action="{% url 'search' %}" method="get" class="form-inline my-1 my-md-0">
          <input name="query" class="form-control" type="text" placeholder="Paieška">
        </form>
        {% if user.is_authenticated %}
          <ul class="sidebar-nav">
            <li><a class="nav-link" href="#">Mano automobiliai</a></li>
            <li><a class="nav-link" href="{% url 'logout'%}">Atsijungti</a></li>
          </ul>
        {% else %}
          <ul class="sidebar-nav">
            <li><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
            <li><a class="nav-link" href="#">Registruotis</a></li>
          </ul>
        {% endif %}
      {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="text-center">
    <h1>Autoservisas</h1>
    <p>Sveiki atvykę į automobilių priežiūros centrą</p>
    <p>Šiuo metu turime:</p>
      <p><strong>Paslaugų:</strong> {{ services_count }}</p>
      <p><strong>Užsakymų:</strong> {{ orders_count }}</p>
      <p><strong>Automobilių:</strong> {{ cars_count }}</p>
    <p>Čia jūs lankotės {{ num_visits }}-ą kartą.</p>
  </div>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  <br>
  {% if automobiliai %}
      {% for a in automobiliai %}
        <li>
          <a href="{% url 'automobilis' a.id %}">{{ a.id }}</a> {{a.klientas}} - {{a.automobilio_modelis_id}}
        </li>
      {% endfor %}
  {% elif automobilio_modelis %}
      {% for a in automobilio_modelis %}
        <li>
          <a href="{% url 'automobilis' a.id %}">{{ a.id }}</a> ({{a.marke}} - {{a.modelis}})
        </li>
      {% endfor %}
  {% else %}
    <p>Oops. Nieko neradome apie automobilio modelius :(</p>
  {% endif %}
{% endblock %}

templates/uzsakymas.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-4">
    <h1>Užsakymo Nr. {{uzsakymas.id}}</h1>
    {% if uzsakymas %}
      <p><strong>Užsakymas: </strong>{{uzsakymas.uzsakymo_eilute_set.all|join:", "}}</p>
    {% else %}
      <p><strong>Užsakymas:</strong> užsakymas nerastas</p>
    {% endif %}
    <p><strong>Užsakovas:</strong> {{uzsakymas.automobilis_id.klientas}}</p>
    <p><strong>Užsakymo data:</strong> {{uzsakymas.data|date:"Y-d-m"}}</p>
    <p><strong>Valstybinis Nr.:</strong> {{uzsakymas.automobilis_id.valstybinis_nr}}</p>
    <p><strong>Automobilio marke/modelis:</strong> {{uzsakymas.automobilis_id.automobilio_modelis_id.marke}}/{{uzsakymas.automobilis_id.automobilio_modelis_id.modelis}}</p>
    <p><strong>VIN:</strong> {{uzsakymas.automobilis_id.vin_kodas}}</p>
    <hr>
    <p class="{% if uzsakymas.status == 't' %}text-success{% elif uzsakymas.status == 'v' %}text-warning{% elif uzsakymas.status == 'a' %}text-danger{% else %}text-success{% endif %}">
      {{ uzsakymas.get_status_display }}
    </p>
    <a href="{% url 'uzsakymai' %}" class="btn btn-secondary mt-3"> Atgal</a>
  </div>
{% endblock %}

templates/uzsakymu_sarasas.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h1>Užsakymų sarašas</h1>
    {% if uzsakymas_list %}
      <ul class="list-group">
        {% for a in uzsakymas_list %}
          <li class="list-group-item">
            <a href="{{a.id}}">
              {{a.automobilis_id.automobilio_modelis_id}} - {{a.automobilis_id.klientas}}, {{a.automobilis_id.valstybinis_nr}}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Nėra užsakymų</p>
    {% endif %}
  </div>
  <div class="container puslapiai">
    <nav aria-label="...">
      <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; pirmas</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">atgal</a>
          </li>
        {% endif %}

        <li class="page-item disabled">
          <span class="page-link">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
          </span>
        </li>

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">pirmyn</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endblock %}

templates/vartotojo_uzsakymai.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>